"""Initial migration

Revision ID: 70aa8d186b6f
Revises: 
Create Date: 2025-05-25 01:13:07.096041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70aa8d186b6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор комментария'),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=10000), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания комментария'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последнего обновления комментария'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор проекта'),
    sa.Column('name', sa.String(), nullable=False, comment='Название проекта'),
    sa.Column('prefix_name', sa.String(length=5), nullable=False, comment='Префикс проекта'),
    sa.Column('description', sa.String(), nullable=False, comment='Описание проекта'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='ID создателя проекта'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания проекта'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последнего обновления проекта'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Статус активности проекта'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix_name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор задачи'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название задачи'),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Приоритет задачи'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время создания задачи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время последнего обновления задачи'),
    sa.Column('status', sa.Integer(), nullable=False, comment='Статус задачи'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='Дата и время завершения задачи'),
    sa.Column('local_task_id', sa.Integer(), nullable=False, comment='Номер задачи в проекте'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('projects')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
